"""
Domain models, enums, and data schemas for Decline Classification, Policy Engine,
and Action Execution (Phases 2 & 3).
"""
from enum import Enum
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field


class DeclineBucket(str, Enum):
    """Three canonical decline buckets based on Razorpay payment failure taxonomy."""
    SOFT_DECLINE = "SOFT_DECLINE"  # Transient: Insufficient funds, network/bank timeouts. Eligible for auto-retry.
    HARD_DECLINE = "HARD_DECLINE"  # Permanent: Expired card, invalid token/mandate. Requires customer payment method update.
    RISK_FLAG = "RISK_FLAG"        # Risk/Fraud: Issuer risk decline, blacklisted card, security filter. Requires human escalation only.


class DecidedAction(str, Enum):
    """Actions decided by the deterministic policy engine."""
    SCHEDULE_RETRY = "SCHEDULE_RETRY"                        # Queue automated retry with backoff
    NUDGE_PAYMENT_UPDATE = "NUDGE_PAYMENT_UPDATE"            # Trigger customer self-serve update flow
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"                  # Halt automation and route to compliance/risk operations
    NO_ACTION_ALREADY_STOPPED = "NO_ACTION_ALREADY_STOPPED"  # Idempotency guard: subscription already terminal/stopped


class ActionExecutionType(str, Enum):
    """Actual recovery action executed in Phase 3."""
    RETRY_PAYMENT = "RETRY_PAYMENT"
    SEND_EMAIL_NUDGE = "SEND_EMAIL_NUDGE"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    HOLD_DND = "HOLD_DND"
    BLOCKED_OPT_OUT = "BLOCKED_OPT_OUT"
    BLOCKED_LIFETIME_CAP = "BLOCKED_LIFETIME_CAP"
    NO_ACTION = "NO_ACTION"


class ActionExecutionStatus(str, Enum):
    """Outcome of the recovery action execution."""
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SENT = "SENT"
    FLAGGED_FOR_HUMAN_REVIEW = "FLAGGED_FOR_HUMAN_REVIEW"
    HELD_DND = "HELD_DND"
    BLOCKED = "BLOCKED"


class SubscriptionLifecycleState(str, Enum):
    """State tracking for subscription recovery lifecycle."""
    ACTIVE_RECOVERY = "ACTIVE_RECOVERY"                      # Retries ongoing within safety bounds
    STOPPED_MAX_ATTEMPTS = "STOPPED_MAX_ATTEMPTS"            # Terminal: Hit max retry attempts (3)
    ESCALATED_HUMAN_REVIEW = "ESCALATED_HUMAN_REVIEW"        # Terminal: Risk flag detected
    AWAITING_CUSTOMER_UPDATE = "AWAITING_CUSTOMER_UPDATE"    # Waiting on customer card/mandate fix
    RESOLVED = "RESOLVED"                                    # Payment recovered successfully


class ExtractedFailureData(BaseModel):
    """Normalized failure parameters extracted from Razorpay webhook payloads."""
    event_type: str
    event_id: Optional[str] = None
    subscription_id: Optional[str] = None
    payment_id: Optional[str] = None
    customer_id: Optional[str] = None
    customer_email: Optional[str] = None
    error_code: Optional[str] = None
    error_description: Optional[str] = None
    error_source: Optional[str] = None
    error_step: Optional[str] = None
    error_reason: Optional[str] = None
    subscription_status: Optional[str] = None
    auth_attempts: Optional[int] = None
    raw_entity: Dict[str, Any] = Field(default_factory=dict)


class ClassificationResult(BaseModel):
    """Output of the decline classifier."""
    bucket: DeclineBucket
    matched_field: str
    matched_rule: str
    reasoning: str
    error_code: Optional[str] = None
    error_reason: Optional[str] = None


class PolicyDecision(BaseModel):
    """Decision output generated by the hard-coded policy engine."""
    action: DecidedAction
    bucket: DeclineBucket
    subscription_id: str
    attempt_number: int
    retry_delay_seconds: Optional[int] = None
    lifecycle_state: SubscriptionLifecycleState
    is_terminal: bool
    reasoning: str
    policy_rule_id: str


class ComplianceCheckResult(BaseModel):
    """Outcome of compliance guardrails evaluation."""
    allowed: bool
    guardrail: Optional[str] = None  # 'DND', 'OPT_OUT', 'LIFETIME_CAP'
    reason: str
    rescheduled_at: Optional[str] = None


class PromiseToPayRecord(BaseModel):
    """Customer promise-to-pay commitment record."""
    id: Optional[str] = None
    subscription_id: str
    customer_id: Optional[str] = None
    promised_date: str  # YYYY-MM-DD
    status: str = "PENDING"  # PENDING, CHECKED_IN, FULFILLED, BROKEN
    check_in_count: int = 0
    last_checked_in_at: Optional[str] = None
    notes: Optional[str] = None
    created_at: Optional[str] = None


class AIDiagnosisResult(BaseModel):
    """Structured output from the AI Diagnostician."""
    failure_diagnosis: str = Field(..., description="Likely root cause diagnosis (e.g. temporary_funds_deficit, gateway_timeout, credential_invalid, fraud_risk)")
    recovery_probability: float = Field(..., ge=0.0, le=1.0, description="Predicted empirical recovery probability between 0.0 and 1.0")
    recommended_action: DecidedAction = Field(..., description="Action recommended by AI")
    recommended_delay_hours: int = Field(default=1, ge=0, description="Recommended delay before execution in hours")
    customer_message_strategy: str = Field(default="NONE", description="Strategy: NONE, PAYMENT_LINK_EMAIL, URGENT_CARD_UPDATE, HUMAN_SUPPORT")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence score between 0.0 and 1.0")
    reasoning: str = Field(..., description="Concise diagnostic rationale")
    provider_used: str = Field(default="local_deterministic", description="Identifier of AI Provider used")
    raw_model_response: Optional[Dict[str, Any]] = Field(default=None, description="Raw model payload for auditability")


class PolicyFirewallDecision(BaseModel):
    """Output from the deterministic policy firewall validating an AI recommendation."""
    is_approved: bool = Field(..., description="Whether the AI recommendation was authorized as-is")
    authorized_action: DecidedAction = Field(..., description="The final authorized action that will be executed")
    override_applied: bool = Field(default=False, description="True if policy firewall overrode AI recommendation")
    override_reason: Optional[str] = Field(default=None, description="Reason for policy override (e.g. Risk isolation, Opt-out block, Retry limit)")
    policy_rule_id: str = Field(..., description="Specific policy rule ID enforcing the decision")
    effective_delay_seconds: int = Field(default=0, description="Final authorized backoff delay in seconds")
    lifecycle_state: SubscriptionLifecycleState = Field(..., description="Resulting subscription lifecycle state")
    is_terminal: bool = Field(default=False, description="Whether the subscription is now in a terminal state")
    compliance_details: Optional[ComplianceCheckResult] = None


class AuditLogEntry(BaseModel):
    """Continuous decision-to-outcome audit log entry with AI & Policy Firewall tracking."""
    id: Optional[str] = None
    event_id: Optional[str] = None
    subscription_id: str
    payment_id: Optional[str] = None
    decline_bucket: str
    reasoning: str
    decided_action: str
    attempt_number: int
    retry_delay_seconds: Optional[int] = None
    subscription_lifecycle_state: str
    
    # AI Diagnosis Fields
    ai_diagnosis: Optional[str] = None
    ai_confidence: Optional[float] = None
    ai_recommendation: Optional[str] = None
    ai_provider: Optional[str] = None
    
    # Deterministic Policy Firewall Fields
    policy_decision: Optional[str] = None
    policy_reason: Optional[str] = None
    policy_rule_id: Optional[str] = None
    policy_override_applied: bool = False
    policy_override_reason: Optional[str] = None
    
    # Action Execution & Outcome Tracking
    action_executed: Optional[str] = None
    action_result: Optional[str] = None
    action_details: Dict[str, Any] = Field(default_factory=dict)
    executed_at: Optional[str] = None
    recovered_amount: Optional[float] = None
    
    created_at: Optional[str] = None

